Update develop.yml

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -24,9 +24,9 @@ jobs:
     - run: airflow dags report -v > /tmp/reports.txt
     - run: cat /tmp/reports.txt
     - run: |
-        if grep -Fwq "ERROR" /tmp/reports.txt \
-        then \
-          echo "Error detected" \
-          exit 1 \
-        fi \
+        if grep -Fwq "ERROR" /tmp/reports.txt 
+        then 
+          echo "Error detected" 
+          exit 1 
+        fi 
         
